### ISSUE TITLE
App is crashing because below error.

### ISSUE THREAD

**Issue by shubham-srivastava-goku** [MacKentoch/react-native-beacons-manager#105]
### Version
1.0.7

### Platform
Android

### OS version

android 8.0.0

### Root Cause:

	07-16 12:10:39.225 21328-21727/com.beacontest D/BeaconsAndroidModule: rangingConsumer didRangeBeaconsInRegion, beacons: [id1: ac628574-fd48-47da-8cc1-4d5442dd5b06 id2: 0 id3: 0, id1: b9407f07-0972-7069-626c-650000000000 id2: 0 id3: 0]
	07-16 12:10:39.226 21328-21727/com.beacontest D/BeaconsAndroidModule: rangingConsumer didRangeBeaconsInRegion, region: id1: null id2: null id3: null
	07-16 12:10:39.237 21328-21727/com.beacontest E/AndroidRuntime: FATAL EXCEPTION: IntentService[BeaconIntentProcessor]
		Process: com.beacontest, PID: 21328
		java.lang.RuntimeException: folly::toJson: JSON object value was a NaN or INF
			at com.facebook.react.bridge.NativeArray.toString(Native Method)
			at com.facebook.react.bridge.CatalystInstanceImpl$PendingJSCall.toString(CatalystInstanceImpl.java:65)
			at com.facebook.react.bridge.CatalystInstanceImpl.callFunction(CatalystInstanceImpl.java:281)
			at com.facebook.react.bridge.CatalystInstanceImpl.callFunction(CatalystInstanceImpl.java:276)
			at com.facebook.react.bridge.JavaScriptModuleRegistry$JavaScriptModuleInvocationHandler.invoke(JavaScriptModuleRegistry.java:94)
			at java.lang.reflect.Proxy.invoke(Proxy.java:913)
			at $Proxy5.emit(Unknown Source)
			at com.mackentoch.beaconsandroid.BeaconsAndroidModule.sendEvent(BeaconsAndroidModule.java:339)
			at com.mackentoch.beaconsandroid.BeaconsAndroidModule.access$200(BeaconsAndroidModule.java:37)
			at com.mackentoch.beaconsandroid.BeaconsAndroidModule$2.didRangeBeaconsInRegion(BeaconsAndroidModule.java:281)
			at org.altbeacon.beacon.BeaconIntentProcessor.onHandleIntent(BeaconIntentProcessor.java:68)
			at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
			at android.os.Handler.dispatchMessage(Handler.java:105)
			at android.os.Looper.loop(Looper.java:164)
			at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by ShaileshPrajapati-BTC** [comment]
same issue

**Comment by TimFinucane** [comment]
This is fixed for me in master

**Comment by Brayyan** [comment]
Same issue , do you have any idea why?
