### ISSUE TITLE
Android application crashing on monitoring region when input uuid is null 

### ISSUE THREAD

**Issue by rostislav-simonik** [MacKentoch/react-native-beacons-manager#53]
### Version
1.0.7

### Platform
Android

### Steps to reproduce
1. start monitoring region with uuid = null   

### Expected behavior
Should report didEnterRegion, didExitRegion

### Actual behavior
Application is crashing 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.altbeacon.beacon.Identi
                            fier.toString()' on a null object reference
                         E      at com.mackentoch.beaconsandroid.BeaconsAndroidModule.createMonitoringResponse(BeaconsAndroidModule.java:2
                            33)
                         E      at com.mackentoch.beaconsandroid.BeaconsAndroidModule.access$100(BeaconsAndroidModule.java:37)
                         E      at com.mackentoch.beaconsandroid.BeaconsAndroidModule$1.didEnterRegion(BeaconsAndroidModule.java:216)
                         E      at org.altbeacon.beacon.BeaconIntentProcessor.onHandleIntent(BeaconIntentProcessor.java:88)
                         E      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                         E      at android.os.Handler.dispatchMessage(Handler.java:102)
                         E      at android.os.Looper.loop(Looper.java:135)
                         E      at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by rostislav-simonik** [comment]
#54 Fix for given issue.
